### ISSUE TITLE
Crash when creating new app when a starter app is not deployed with the dashboard

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-dashboard#101]
Instead of hiding the button "Build New App" or replacing it with directions to do via the terminal, if a starter app is not deployed with the dashboard, clicking "Build New App" results in a crash. First reported in https://github.com/OSC/ood-dashboard/issues/99

>Experienced two issues with this. One in development and another in existing production app. They appear to be different errors but they may stem from the same cause.
>
>To recreate:
>"Develop" dropdown -> "My Sandbox Apps" -> click "Build New App" -> Fill out form and click "Submit"
>
>In development:
>
>![newproducterror](https://cloud.githubusercontent.com/assets/2374718/21268235/cc8d455c-c37b-11e6-9b03-64c14415419c.png)
>

**Comment by nickjer** [comment]
Creating the starter app was part of the deployment instructions for the dashboard. But I see they have been removed.

**Comment by ericfranz** [comment]
They are here: https://github.com/OSC/ood-dashboard/wiki/App-Sharing

**Comment by ericfranz** [comment]
No longer relevant.
