### ISSUE TITLE
Consider removing "Icon" label from table header

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-dashboard#103]
Just an aesthetic preference, but the awesim dashboard might look a little cleaner without the "Icon" label. The text itself seems unnecessary.

Before:

![iconwithlabel](https://cloud.githubusercontent.com/assets/2374718/21277922/8d96936e-c3a6-11e6-9b29-aa1e60bbf650.png)

After:

![iconwithoutlabel](https://cloud.githubusercontent.com/assets/2374718/21277923/90172fa4-c3a6-11e6-8fc0-a0e8e188aa06.png)

**Comment by ericfranz** [comment]
Looks like a simple fix. I'm okay with this.

**Comment by nickjer** [comment]
Another possibility is putting the App name/link right above the description. Otherwise the "App" column has a lot of whitespace.

**Comment by nickjer** [comment]
It would also give the MOTD more space instead of it crammed to the side.

**Comment by brianmcmichael** [comment]
The icons themselves should also include clickable links to the app.

**Comment by nickjer** [comment]
Another suggestion, make the title of the app plain text (not a link) and increase its font size. Then add a "Launch" button underneath the icon (or maybe somewhere else).

**Comment by brianmcmichael** [comment]
I like that. Maybe out of scope for this issue. Maybe @ericfranz should weigh in.

**Comment by ericfranz** [comment]
Go ahead and add a mock screenshot of options. I prefer the title of the app be the launch link and the icon be a link too
