### ISSUE TITLE
Dashboard and dashboard link aren't the same.

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-dashboard#11]
- Navigate to `ondemand.osc.edu`
- Browser displays `https://ondemand.osc.edu/pun/sys/dashboard`
- Hover over "OSC OnDemand"
- Link location is `https://ondemand.osc.edu/pun/sys/dashboard/` (note trailing slash)

Reported at: https://github.com/OSC/ondemand-testing/issues/31#issuecomment-245615415

**Comment by ericfranz** [comment]
not a bug. `root_path` is used for this link
