### ISSUE TITLE
Consider displaying actual inputs of shell commands.

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-dashboard#110]
The command strings displayed to the user are currently hardcoded at:

https://github.com/OSC/ood-dashboard/blob/3080b871f93c7413d528beff02587652fb2d4ec5/app/views/products/show.html.erb#L45-L47

This strikes me as problematic because the actual commands are included in the controller at:

https://github.com/OSC/ood-dashboard/blob/3080b871f93c7413d528beff02587652fb2d4ec5/app/controllers/products_controller.rb#L110-L115

So the output displayed is not necessarily the actual input used by the command. Currently, if there's an update to one of the commands, the command displayed to the user does not automatically reflect this.

Is there a reason that either the "input" output of the `popen3` command can't be displayed here? (i.e. it's not available to the view yet?) Or can the command hash and strings be added to the `Product` model and accessed in the controller and view from there so that at least they're in one place?

**Comment by nickjer** [comment]
The disconnect between the commands is due to the fact that the commands are run under different shell environments.

The commands in the controller are run under the PUN environment, where the necessary Software Collections packages are loaded.

The commands in the view are meant to be copied and pasted by the developer into his/her shell if necessary. As the default login shell does not have the same environment as the PUN, the developer will then need to run slightly different commands that the app runs.

One solution would be to set up the developer shell to run under the same shell environment as the PUN. This is a non-trivial problem right now that would require further discussion.

>Is there a reason that either the "input" output of the popen3 command can't be displayed here?

Not sure what you mean by "output" as the output is displayed to the user in real time.

**Comment by brianmcmichael** [comment]
> The disconnect between the commands is due to the fact that the commands are run under different shell environments.

Sure, but my concern is that these are in different places. So if our controller is updated it's not evident that the view will need to be updated.

I would suggest something like a nested hash in the `Product` model. Something like:

```
@@commands = {
    bundle_install:    { command: [{"HOME" => ""}, "bin/bundle install --path=vendor/bundle"], "text: scl enable rh-ruby22 nodejs010 -- bin/bundle install --path=vendor/bundle" },
    precompile_assets: { command: [{"RAILS_ENV" => "production"}, "bin/rake assets:clobber && bin/rake assets:precompile && bin/rake tmp:clear"], text: "RAILS_ENV=production scl enable rh-ruby22 nodejs010 -- <<< 'bin/rake assets:clobber && bin/rake assets:precompile && bin/rake tmp:clear'" },
    restart_app:       { command: ["mkdir -p tmp && touch tmp/restart.txt && echo 'Done!'"], text: "mkdir -p tmp && touch tmp/restart.txt" }
  }
```

Then we can access via `Product.commands[:bundle_install][:command]` in the controller and `Product.commands[:bundle_install][:text]` (or something like that) in the view without having all of the knowledge distributed to views and controllers.

> Not sure what you mean by "output" as the output is displayed to the user in real time.

Open3 has a `stdin` pipe, which I was suggesting be output to the user here if possible, I'm not totally clear how that works right now so that's why it's tagged as a question.

**Comment by ericfranz** [comment]
At the point where a nested hash is considered, the better solution is a new "CliCommand" object, with the appropriate attributes. Product instances have a list of these and the buttons are generated by iterating over the list.

That is addressed by this issue #102

**Comment by nickjer** [comment]
Refactoring it is discussed here https://github.com/OSC/ood-dashboard/issues/102

**Comment by brianmcmichael** [comment]
Closing, track in #102 instead.
