### ISSUE TITLE
Break up app dropdowns by cluster

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-dashboard#112]
There are requests to use software on Owens (i.e., Abaqus). But we currently only supply an Abaqus app that uses the Oakley cluster.

@basilgohar suggested in the past that we display the apps available grouped by clusters in the dashboard.

So one possibility would be breaking up the "Desktop Apps" dropdown in the dashboard into: Oakley Apps, Ruby Apps, Owens Apps, VDI Apps. And the dropdowns only appear if there are any apps that the user has access to in them.

The other option is the apps themselves are responsible for letting the user choose the cluster. So an Abaqus app would have in the VNCSim app a dropdown with the options:

  - Abaqus/CAE 6.14 (Software Rendering) - Oakley
  - Abaqus/CAE 6.14 (Hardware Rendering) - Oakley
  - Abaqus/CAE 2016 (Software Rendering) - Oakley
  - Abaqus/CAE 2016 (Hardware Rendering) - Oakley
  - Abaqus/CAE 2016 (Software Rendering) - Owens
  - Abaqus/CAE 2016 (Hardware Rendering) - Owens

But I think this will be a fairly cluttered approach.

**Comment by ericfranz** [comment]
Its possible to give the user the option to specify the cluster and software version in vncsim itself, without having a single cluttered dropdown. But would require some thought.

**Comment by ericfranz** [comment]
We do have an inconsistency. Some apps are responsible for allowing the user to submit jobs (or run) on different clusters (My Jobs, Active Jobs, app kit workflow apps). Others ask that the user choose the cluster from the Dashboard (Shell, Desktop and VDI apps).

If we do have Owens Apps, Ruby Apps, Owens Apps, VDI apps dropdowns, we could move the shell access app links to these dropdowns as well.

But then where would "System Status" go?

**Comment by brianmcmichael** [comment]
Why would it need to be one list? It seems like that could be broken into three components with defaults for each.

* Server Dropdown
  * Oakley (Default)
  * Owens
* Version Dropdown
  * CAE 6.14    [Not selectable/visible when Owens selected?]
  * CAE 2016 (Default)
* Options Dropdown (or checkbox)
  * Hardware (Default?)
  * Software

There wouldn't be much thought needed since it's pretty fine-grained at that point. Not sure how that would look for something like COMSOL server that doesn't have the hardware/software optional configs though.

**Comment by ericfranz** [comment]
>The other option is the apps themselves are responsible for letting the user choose the cluster. So an Abaqus app would have in the VNCSim app a dropdown with the options:
>
>Abaqus/CAE 6.14 (Software Rendering) - Oakley
>Abaqus/CAE 6.14 (Hardware Rendering) - Oakley
>Abaqus/CAE 2016 (Software Rendering) - Oakley
>Abaqus/CAE 2016 (Hardware Rendering) - Oakley
>Abaqus/CAE 2016 (Software Rendering) - Owens
>Abaqus/CAE 2016 (Hardware Rendering) - Owens

How would this work? What would the web form look like, and what would the resulting YAML look like?

**Comment by nickjer** [comment]
> What would the web form look like

![image](https://cloud.githubusercontent.com/assets/4260509/21941123/4b635e0a-d995-11e6-9e15-473a34df4344.png)

> and what would the resulting YAML look like?

https://github.com/OSC/bc_osc_abaqus/blob/master/app.yml

**Comment by ericfranz** [comment]
No longer relevant.
