### ISSUE TITLE
MOTD runs off of window for smaller screens

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-dashboard#115]
Long links in the MOTD run off my browser window, see below:

![image](https://cloud.githubusercontent.com/assets/4260509/22113702/2b3a8dde-de35-11e6-8bc5-2c5bd491245c.png)

Not sure how to improve on this. Maybe give the MOTD panel itself a horizontal scrollbar or the message itself. Similar to how in GitHub markdown, long blocks of code get their own scrollbar:

![image](https://cloud.githubusercontent.com/assets/4260509/22113771/70923382-de35-11e6-8dd0-08ea409e7b7e.png)

**Comment by brianmcmichael** [comment]
If it's just the links, one option would be to truncate the visible portion with CSS.

I do this in Job Status at https://github.com/AweSim-OSC/osc-jobstatus/blob/c1d6069f69e85922e63a799058bb2cc211ffadbd/app/assets/javascripts/application.js.erb#L37

Which results in:

![truncate](https://cloud.githubusercontent.com/assets/2374718/22114596/14903ec8-de38-11e6-8c92-097c63614d39.png)
