### ISSUE TITLE
Display folder name on delete app modal.

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-dashboard#119]
When I go to delete an app, I'm prompted to type the full name of the folder I want to delete.

At this point, the full name is sometimes hidden behind the modal, so I either have to close the box or try to remember the folder name, which may be complex. It may be appropriate to display the folder name that we want them to type here.

![deleteapp](https://cloud.githubusercontent.com/assets/2374718/22157667/90de5518-df06-11e6-8830-9fb043b34bd5.png)

**Comment by nickjer** [comment]
I have no strong preference either way. I originally left the directory name off to make it that much harder for a developer to delete the app as the consequences could be pretty bad.

I'd wait for feedback from @ericfranz and @basilgohar before making any pull requests.

**Comment by brianmcmichael** [comment]
The github delete confirmation, for example, includes the text.

![delete](https://cloud.githubusercontent.com/assets/2374718/22174549/5da914b8-dfaf-11e6-94b1-5c702f6ebac7.png)
