### ISSUE TITLE
Display authenticated user on Dashboard

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-dashboard#12]
Currently we only display the mapped user on the Dashboard:

![image](https://cloud.githubusercontent.com/assets/4260509/18392458/db9b1e00-767f-11e6-815a-ea6ae831ed34.png)

But users don't know the original mapping that led them to this account if they are automatically logged in. Displaying the authenticated user here as well would be helpful.

![image](https://cloud.githubusercontent.com/assets/4260509/18392514/0f8f024e-7680-11e6-8124-ab60c0e44ea0.png)

**Comment by ericfranz** [comment]
> Displaying the authenticated user here as well would be helpful

Unfortunately, OIDC_Claim headers are not all the same for different CILogon IDPs, and other authentication solutions won't have these headers.

Plus, where will this go on the nav bar? Its already a bit crowded.

Needs more technical and functional design.

**Comment by ericfranz** [comment]
We strip the claim headers now. Not doing.
