### ISSUE TITLE
dataroot for awesim and ondemand are the same

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-dashboard#121]
Two dev dashboards one configured for AweSim, one for OnDemand:

```
efranz@webdev02:~/ondemand/dev/dashboard (launchpad)$ RAILS_ENV=production bin/rails c
Loading production environment (Rails 4.2.7.1)
=> Unable to load pry
irb(main):001:0> ENV['OOD_DATAROOT']
=> "/users/PZS0562/efranz/ondemand/data/sys/dashboard"
irb(main):002:0> ENV['OOD_PORTAL']
=> "ondemand"
irb(main):003:0> 
```

```
efranz@webdev02:~/awesim/dev/dashboard (polish)$ RAILS_ENV=production bin/rails c
Loading production environment (Rails 4.2.7.1)
=> Unable to load pry
irb(main):001:0> ENV['OOD_DATAROOT']
=> "/users/PZS0562/efranz/ondemand/data/sys/dashboard"
irb(main):002:0> ENV['OOD_PORTAL']
=> "awesim"
irb(main):003:0> 
```

Solution? The default .env.production sets certain values based on variables like `OOD_PORTAL`. Without a shared OOD-wide env such as is mentioned in https://github.com/OSC/ood_appkit/issues/31

Too bad there isn't a `.env.local.production` that can be used.

A solution that doesn't involve multiple .env.production files is desired.

**Comment by ericfranz** [comment]
Whatever solution we can do to avoid multiple .env.production files, so we can have a sensible default .env.production file, should be used on https://github.com/OSC/ood-myjobs and https://github.com/OSC/ood-activejobs so for those apps we can have a sensible default .env.production file.

**Comment by ericfranz** [comment]
In fact, dotenv-2.2.0 released Jan 27, 2017, supports a local file per environment:  https://github.com/bkeepers/dotenv/pull/281 and https://github.com/bkeepers/dotenv/blob/7bc34315414e0af5e668f8535a9321446e615e58/lib/dotenv/rails.rb#L24-L31

```
    def load
      Dotenv.load(
        root.join(".env.#{Rails.env}.local"),
        root.join(".env.local"),
        root.join(".env.#{Rails.env}"),
        root.join(".env")
      )
    end
```

>`dotenv-rails` will load the following files, starting from the bottom. The first value set (or those already defined in the environment) take precedence:
>
>- `.env` - The Original®
>- `.env.development`, `.env.test`, `.env.production` - Environment-specific settings.
>- `.env.local` - Local overrides. This file is loaded for all environments _except_ `test`.
>- `.env.development.local`, `.env.test.local`, `.env.production.local` - Local overrides of environment-specific settings.
>

**Comment by ericfranz** [comment]
One question to test:

If I set `OOD_PORTAL="awesim"` in `.env.production.local`, can I do this in `.env.production`:

    OOD_DATAROOT=$HOME/$OOD_PORTAL/data/sys/dashboard

Will `$OOD_PORTAL` be set to `~/awesim/data/sys/dashboard`?

**Comment by ericfranz** [comment]
We can do tests to confirm how using dotenv should work, and how we can possibly modify it, by writing a few simple tests by writing test env files in tmpdir and using Dotenv.load directly (or in Rails, Dotenv::Railtie.load) in a block where you use a clean environment: 

```ruby
test_env = Bundler.with_clean_env { Dotenv::Railtie.load; ENV }

# now add assertions that certain values were set
```

**Comment by nickjer** [comment]
> One question to test:
>
> If I set `OOD_PORTAL="awesim"` in `.env.production.local`, can I do this in `.env.production`:
>
> ```
> OOD_DATAROOT=$HOME/$OOD_PORTAL/data/sys/dashboard
> ```
>
> Will `$OOD_PORTAL` be set to `~/awesim/data/sys/dashboard`?

I think you meant `$OOD_DATAROOT` in that last sentence. And from previous tests this will not be true. It seems each `.env` file loaded is in a completely separate fork with its own environment variables and cannot affect another `.env` file. The global environment variables can be used though.

**Comment by nickjer** [comment]
One option is having a `.env.production.erb` template and have the `bin/setup` produce a `.env.production` based on `OOD_PORTAL`. Something along the lines of:

```erb
# .env.production.erb
OOD_PORTAL="<%= ENV["OOD_PORTAL"] || "ondemand" %>"
APP_TYPE="sys"
APP_NAME="$(basename $PWD)"

APP_TOKEN=$APP_TYPE/$APP_NAME
OOD_DATAROOT=$HOME/$OOD_PORTAL/data/$APP_TOKEN
RAILS_RELATIVE_URL_ROOT=/pun/$APP_TYPE/$APP_NAME

SECRET_KEY_BASE=53e7db1a78270f3e7ab2c09f7b84972f9ee1f6462ba6327f8cfecb9b01d10b58d849ef0cde0ec65fd106851442c08064c2649f6a2ee89f7ad2f957210d4e3d83
```

and you'd remove the `OOD_PORTAL` from the `.env.local.*`.

The `bin/setup` can be made smart enough to read the `OOD_PORTAL` from the `.env.production` if this file exists and `$OOD_PORTAL` does not exist. So the developer doesn't have to keep calling...

```ruby
OOD_PORTAL=awesim bin/setup
```

He'd only need to do it on the first call.

**Comment by nickjer** [comment]
Another option is we design a convention for the dataroot in `ood_appkit`, so if `APP_TOKEN` is present:

```ruby
self.dataroot = ENV['OOD_DATAROOT'] || ENV['RAILS_DATAROOT']
self.dataroot ||= "#{ENV['HOME']}/#{ENV['OOD_PORTAL'] || "ondemand"}/data/#{ENV['APP_TOKEN']} if ENV['APP_TOKEN']
```
