### ISSUE TITLE
Perform a page refresh after bundle installing a development app.

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-dashboard#124]
After a bundle install is performed, the error message that tells me to perform a bundle install command remains.

![jobstatus](https://cloud.githubusercontent.com/assets/2374718/23028239/cda8283c-f434-11e6-97b5-5f402d0d5711.png)

The simplest solution may just be to perform a page refresh after the user closes the bundle install window, so that the logic that detects the errors re-runs.

**Comment by ericfranz** [comment]
Not focusing on developer dashboard right now.
