### ISSUE TITLE
Document the global announcements

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-dashboard#125]
Maybe this is already done, but I am unable to find the documentation on how to add global announcements.

**Comment by nickjer** [comment]
This is the corresponding commit:

https://github.com/OSC/ood-dashboard/commit/ba7c173772ca1fb216a924d1a22e8e79662aa883

**Comment by ericfranz** [comment]
https://github.com/OSC/ood-dashboard/wiki/Site-Wide-Announcement
