### ISSUE TITLE
README doesn't use sudo command

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-dashboard#133]
Need to use `sudo` command here:

![image](https://cloud.githubusercontent.com/assets/4260509/23563894/ad6e6dfe-0016-11e7-9fac-0ab659a5a2d4.png)

**Comment by brianmcmichael** [comment]
Fixed by https://github.com/OSC/ood-dashboard/commit/4360663a4127e73136bc4726ecaf212c71adfcaf
