### ISSUE TITLE
Add ability to set git remote via the web interface.

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-dashboard#136]
Currently, the app allows cloning from a git remote. In this case, the git remote is then set by the app.

If an app is created by the template, there is no web-based option to set the git remote. The app does, however, complain that a git remote is not set. The only way to set the git remote in this situation is via the terminal.

Propose adding a webby-clicky option to perform the `git remote set-url` command via a view.

**Comment by nickjer** [comment]
I believe this has been fixed. When I click "Edit Metadata" I see a field that allows one to set the git remote.
