### ISSUE TITLE
MOTD not respecting lists

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-dashboard#137]
Lists appear as a single sentence and are harder to read:

![image](https://cloud.githubusercontent.com/assets/4260509/23754101/d19457b0-04a9-11e7-81fd-0dc34461e978.png)

![image](https://cloud.githubusercontent.com/assets/4260509/23754111/dacbed16-04a9-11e7-90ac-26e752732a18.png)

**Comment by brianmcmichael** [comment]
A space is required between the previous sentence and the start of the bullet list to be proper markdown.

I think fixing the motd to say:

```
2017/01/23
--- TRY ONDEMAND, OSC'S WEB PORTAL

Our app-based web portal, OnDemand, is at ondemand.osc.edu, you can:

* Access and manage all your files
* Get terminal access for any of our clusters in a browser window
* Create and submit jobs with our Job Constructor
* Access our resources in a virtual desktop environment
```

should fix this issue.

**Comment by ericfranz** [comment]
That is not proper markdown.

If instead of:

```
Our app-based web portal...
* Access
```

it was

```
Our app-based web portal...

* Access
```

It would be fine.

There may be a setting in redcarpet to fix this in the short term. But we probably should move away from this propriety formatting to an RSS feed #63.
