### ISSUE TITLE
App Sharing Permissions section seems to be broken

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-dashboard#141]
Developer reported trying to remove a group from the Groups permissions list. The page refreshes and it says "Permission was successfully destroyed." However, the group attempted to be removed remained in the list and running nfs4_getfacl from the command line showed the group was never removed.

**Comment by nickjer** [comment]
Is it the primary group?

**Comment by nickjer** [comment]
Also can you say the app location on the file system? Also what group he/she tried to remove?

**Comment by ericfranz** [comment]
From Paul G:

>Basically I remove PYS0218 group, see the confirmation, refresh, and still see the group. Likewise checking the permission manually shows it exists. 
Also, when I delete an app, it simply deletes the corresponding directory correct?
>
>
>![image](https://cloud.githubusercontent.com/assets/512333/25440984/fb2a423e-2a6e-11e7-9ab8-b4baedaf41d8.png)

**Comment by nickjer** [comment]
It seems Paul must have manually added that nfs4 permission previously. The Dashboard app doesn't play well with the myriad of permissions that nfs4 comes with. It will only add `rx` or remove `rx` for a specified user or group. Also nfs4 doesn't raise any errors when you try to remove an ACL that doesn't match, so error detection is difficult.

My suggestion is that Paul manually removes that ACL and only use the Dashboard to manage ACLs from now on.

**Comment by ericfranz** [comment]
Can't reproduce.
