### ISSUE TITLE
Design iHPC in OOD

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-dashboard#149]
Design next steps

1. design for batch_connect library generalization and (possible) integration into ood_core
   * example configuration: font paths, locations of novnc, script defaults, environment defaults, etc.
2. batch connect app generalization plan
   * example of different types of apps
      * what all three desktop and vdis would look like
      * what rstudio (server example), paraview (vdi example), and abaqus cae (ihpc example) would look like
      * one example in progress at /users/appl/jnicklas/ttt/example-bc-app
3. design for dashboard integration
   * example https://github.com/OSC/ood-dashboard/pull/142
   * design needs more details - what does it look like with all these batch connect apps?
4. design ood_connect: identify the changes required to make native available OR decide on native tab providing connection information for windows if ood_connect is not yet released
5. documenting the installation process (all the dependencies to install to work)
   * would the dashboard offer a method to "test" the installation, for example, submit an iHPC job that just verifies what is available, and reports to the user through the interface
6. beta site engagement: find several sites outside of OSC to work with us on getting this feature added

**Comment by nickjer** [comment]
This probably needs to be broken up into tasks.

**Comment by ericfranz** [comment]
https://osu.app.box.com/notes/169197248098 has the task list
