### ISSUE TITLE
Title and description are not preserved when creating a new product

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-dashboard#163]
Requires app sharing to be enabled.
Steps to reproduce:

Develop -> My Sandbox Apps (Development)
Click Button -> New Product
Click Button -> Build New App
Enter information and click "Submit"

Only the directory is used. The app title and description entered are ignored and replaced with the defaults.

![nodesc](https://user-images.githubusercontent.com/2374718/26984598-0298a3d2-4d0e-11e7-8d27-7fe986c218e7.png)

**Comment by ericfranz** [comment]
Not focusing on developer dashboard right now.
