### ISSUE TITLE
iHPC app with one subapp does not display proper title in nav

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-dashboard#170]
This will be a problem for sites that have only one cluster that OnDemand serves.

### Steps to reproduce:

```
sudo to wiag user
cd ~/ood_portals/awesim_test/sys
cp -r bc_desktop_v2/ bc_osc_owens_desktop_v2
rm bc_osc_owens_desktop_v2/local/oakley.yml bc_osc_owens_desktop_v2/local/ruby.yml bc_osc_owens_desktop_v2/local/vdi-*
```

Then access dashboard. You will see this owens desktop v2 listed as "Desktops" in the nav bar. Click it. The breadcrumbs say "Owens Desktop". However, the list of apps on the left and the dropdown nav at the top both say "Desktops".

<img width="828" alt="screen shot 2017-06-15 at 5 27 36 pm" src="https://user-images.githubusercontent.com/512333/27202527-fb17af04-51ef-11e7-843a-f31d772295e5.png">
<img width="820" alt="screen shot 2017-06-15 at 5 27 27 pm" src="https://user-images.githubusercontent.com/512333/27202528-fb18cd1c-51ef-11e7-9bdb-80aa6d9eca45.png">

**Comment by nickjer** [comment]
I don't think this is a bug in the Dashboard, but more of a drawback of using the Dashboard to handle the batch connect apps.

Although one of our discussions was having the Interactive Apps handle its own routing for app discovery, that way it can be more flexible with how it determines a valid Batch Connect App.

**Comment by ericfranz** [comment]
One solution: 

1. `OodApp#batch_connect` returns `BatchConnect::App`
2. a factory method for building a router from an app token is provided

**Comment by ericfranz** [comment]
This has been fixed.
