### ISSUE TITLE
iHPC OSC non Ruby users can access Ruby through quick

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-dashboard#172]
For Ruby Desktop, we are currently checking the cluster config to see if the user is allowed to use this app, and if not, disabling the app listed in the subapps list. For Ruby VDI, since it shares the quick cluster with Oakley and Owens, the cluster config contains no validations to prevent the user accessing.

Several solutions

A:

1. have 3 cluster configs for the quick cluster. like before
2. add validation to cluster based on group membership

B:

1. chmod 750 and chgrp ruby for the ruby vdi
2. ensure that code handles loading batch connect subapps list gracefully (doesn't crash)

C:

1. Allow an app be able to specify it relies on access to another cluster (like Ruby VDI relies on access to ruby even though it uses quick to submit the job).

**Comment by ericfranz** [comment]
Note this just lets them run a Ruby VDI session. They would still be prevented from submitting jobs so it isn't as serious of an issue.

**Comment by nickjer** [comment]
Another option is app-specific ACLs re-using the code currently used to parse cluster configs in `ood_core`. So an example `local/vdi-ruby.yml` would look like:

```yaml
title: "Ruby VDI"
...

acls:
  - adapter: group
    groups: [ ruby ]
```

**Comment by ericfranz** [comment]
Wont fix. This hasn't been a problem.
