### ISSUE TITLE
Weird view if no system batch connect apps

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-dashboard#173]
Without system batch connect apps the views look odd:

![screenshot from 2017-06-20 13-15-37](https://user-images.githubusercontent.com/4260509/27346282-b0540994-55ba-11e7-8acc-c27fc08d3ca4.png)

**Comment by ericfranz** [comment]
This is related to #259. This appears when you don't have any valid system batch connect apps BUT you have batch connect apps in your sandbox. If we fix #259 then when developing a batch connect app I won't have a link in the dropdown menu to access interactive sessions!
