### ISSUE TITLE
Developer generated app includes `@import 'pages'`

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-dashboard#174]
Creating a "new" app via the dashboard generator includes an `@import 'pages'` style, but no associated `pages` stylesheet. 

This should probably be removed from the template or commented out for reference.

![invalid import](https://user-images.githubusercontent.com/2374718/27351628-0230f6da-55cc-11e7-97fc-441b14ddef89.png)

**Comment by nickjer** [comment]
Maybe this issue should be in the following repo:

https://github.com/AweSim-OSC/rails-application-template

Unless you feel it is a bug in the Dashboard app.

**Comment by nickjer** [comment]
Or do we need to update the currently deployed Rails template?

**Comment by brianmcmichael** [comment]
I thought that the currently deployed dashboard includes a pre-packaged template. I wasn't aware that it's still drawing from the rails-application-template.

**Comment by nickjer** [comment]
I would need to refresh my memory here, but I believe part of the Dashboard deployment process (which we've been slipping on) is to download the latest application template.

https://github.com/OSC/ood-dashboard/wiki/App-Sharing

**Comment by ericfranz** [comment]
We now only support cloning from a git repo.
