### ISSUE TITLE
Namespace batch_connect dataroot

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-dashboard#181]
As @ericfranz pointed out we will need to namespace the dataroot used by the batch_connect namespaced code. This can affect active sessions (queued and running) so a in-situ migration may need to be applied.

**Comment by ericfranz** [comment]
Do something like this migration one time at dashboard startup, in an initializer:

```
cd $OOD_DATAROOT # cd ~/awesim/data/sys/dashboard
if "db" exists and is not a symlink:
  mkdir batch_connect
  mv db sys dev batch_connect
  ln -s batch_connect/db db
  ln -s batch_connect/dev dev
  ln -s batch_connect/sys sys
```

The symlinks would let any queued or held sessions still start and write conn info to the appropriate location.
