### ISSUE TITLE
Refactor the Products code

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-dashboard#188]
A few issues with the Products code that may need to be refactored:

- It may be best to namespace the portion of the code that handles app development from the rest of the dashboard similar to what we do for iHPC apps.
- Utilize form objects for creating new apps as it is currently very difficult to add a new app generator (e.g., adding an iHPC app generator) as is.

**Comment by ericfranz** [comment]
Discussed offline. The decision was to use a form object for the new iHCP template, and leave the existing code untouched. After that code is written, it may be more instructive as to a refactor that may make more sense.
