### ISSUE TITLE
Browser requirements warning appears only on main page

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-dashboard#189]
This is just a question and not an issue. I noticed that we display the browser requirements warning on the main Dashboard index page as such:

![screenshot from 2017-07-10 14-22-07](https://user-images.githubusercontent.com/4260509/28033159-2e499c22-657b-11e7-8d1a-114b7e009c00.png)

But we do not display it on any other Dashboard page. For example it is not displayed on the iHPC pages or error pages.

Is this intended behavior? Or do we want to display this on every Dashboard page (i.e., make it part of the layout)?

**Comment by ericfranz** [comment]
Lets not worry about this right now.
