### ISSUE TITLE
Error when `motd` is is empty file.

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-dashboard#19]
When installing ood on a new machine, if there is no `motd` an exception is thrown.

1.) Simple fix is to update to return 0 messages if the file is missing or corrupt.

2.) Next step would be to remove mention of the "Message of the Day" if the file is missing or corrupt.

3.) May want to consider converting to RSS or something since the `motd` is so highly dependent on a formatting structure provided to OSC client services. We should not be prescribing a MOTD format for other sites.

**Comment by ericfranz** [comment]
@brianmcmichael you seem to have a handle on this problem; how about:

![screen shot 2016-11-02 at 10 54 03 am](https://cloud.githubusercontent.com/assets/512333/19933699/b6ab4800-a0ea-11e6-882d-1894a4eb58ca.png)

```html
<h3>Message of the Day</h3>
<hr>
<p class="lead">No messages available.</p>
```

I also like the idea of motd => RSS => HTML but I'd open a separate FR for that.
