### ISSUE TITLE
Crash when app sharing disabled by I have sharing directory

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-dashboard#202]
My `.env.local`:

```bash
# .env.local

...

# comment out the below option
#OOD_APP_SHARING=true
```

And confirm I have a sharing directory:

```bash
$ ll -d /var/www/ood/apps/usr/jnicklas/
drwxr-xr-x 2 root root 4096 Sep 23  2016 /var/www/ood/apps/usr/jnicklas/
```

Load the Dashboard:

![screenshot from 2017-07-18 11-55-19](https://user-images.githubusercontent.com/4260509/28326909-0104ee34-6bb0-11e7-804e-76b9d6fd463f.png)

**Comment by ericfranz** [comment]
So thats the Developer menu. That menu should not display if OOD_APP_SHARING is disabled.

**Comment by ericfranz** [comment]
https://github.com/OSC/ood-dashboard/blob/e6d343ecd7895dac8ab0b9356f89d44c9589c421/app/apps/nav_config.rb#L7

The reason you experience this is that https://github.com/OSC/ood-dashboard/blob/e6d343ecd7895dac8ab0b9356f89d44c9589c421/config/initializers/ood.rb.osc.awesim#L14 is incomplete:

```ruby
# don't show develop dropdown unless you are setup for app sharing
NavConfig.show_develop_dropdown = UsrRouter.base_path.directory?
```

should change to

```ruby
NavConfig.show_develop_dropdown = ENV['OOD_APP_SHARING'].present? && UsrRouter.base_path.directory?
```

But the only portal this affects is AweSim. And AweSim's .env.local has OOD_APP_SHARING present.

**Comment by nickjer** [comment]
You are right, it will only affect AweSim at the moment because `NavConfig.show_develop_dropdown` is only overridden in the AweSim initializer.

Another solution may be creating a custom getter in `NavConfig` such as:

```ruby
class NavConfig
  class << self
    attr_accessor :categories

    def show_develop_dropdown
      ENV['OOD_APP_SHARING'].present? && @show_develop_dropdown
    end

    attr_writer :show_develop_dropdown
  end
  self.categories = ["Files", "Jobs", "Clusters", "Interactive Apps"]
  self.show_develop_dropdown = true
end
```

**Comment by ericfranz** [comment]
fixing #212 should fix this defect too, it just needs to be tested to determine that it fixes it

**Comment by basilgohar** [comment]
I was able to get past that error screen by changing from OOD_APP_SHARING to OOD_APP_DEVELOPMENT, but the route still needs to be defined, but now the route won't be presented if OOD_APP_DEVELOPMENT is not enabled (but that was also true for OOD_APP_SHARING).

So, basically, I'd like to be sure that this actually fixes the concern here.  If the development menu is not shown, then those routes will never be fetched to generate the links, so the error should not happen.

**Comment by ericfranz** [comment]
I'd wait till https://github.com/OSC/ood-dashboard/pull/226 completely fulfills all requirements and then check back here.

The crash happens app development is enabled, but app sharing is disabled (i.e. develop dropdown is shown)
