### ISSUE TITLE
How do I start Paraview with the input directory set using the new iHPC?

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-dashboard#203]
From glancing over https://github.com/OSC/ood-dashboard/wiki/iHPC-CLI documentation it seems that the rake task only lets me specify arguments that would otherwise be submitted via the web form. So if an option is not in the web form it cannot be customized using the session context (i.e. custom env vars like we provided with https://github.com/AweSim-OSC/vncsim/pull/103 that could be set via GET or POST param but not be part of the web form).

Is this wrong?

If so, are the only options for creating the ability to launch Paraview with an input directory are:

1. update Paraview iHPC app to accept an optional form text field with the path to the input file, then update both submit.yml to set this to an ENV var and then update the template to use this
2. fork Paraview and modify it (i.e. a custom iHPC app) and then launch it with custom arguments

**Comment by nickjer** [comment]
> So if an option is not in the web form it cannot be customized using the session context.

That is correct. We only allow attributes that can be modified here:

https://github.com/OSC/ood-dashboard/blob/e6d343ecd7895dac8ab0b9356f89d44c9589c421/app/controllers/batch_connect/session_contexts_controller.rb#L64-L67

> 1. update Paraview iHPC app to accept an optional form text field with the path to the input file, then update both submit.yml to set this to an ENV var and then update the template to use this

This is a valid option. Also you can make it a hidden field if you intend on it only being manipulated through the command line and not through the browser.

> 2. fork Paraview and modify it (i.e. a custom iHPC app) and then launch it with custom arguments

Also another valid option. This would also give the developer of the app more control. For instance they can use a different version of Paraview than we support through OnDemand. They can also get fancy and add more Paraview command line options such as:

https://github.com/AweSim-OSC/vftwebapp/blob/9c8646fb2d541ae2b286da8789e9233759dc91f5/jobs/paraview/xstartup#L19
