### ISSUE TITLE
Add a portion of the dev apps to the develop dropdown

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-dashboard#220]
Maybe limit to 10, then have a (see all) at the bottom.
Clicking the app would take you to the details page, at which point you could click "Launch".

**Comment by ericfranz** [comment]
This is a solution but possibly not a helpful one:

https://github.com/OSC/ood-dashboard/pull/225

**Comment by nickjer** [comment]
Just something to think about...

Scanning lots of directories hosted on a shared file system for every HTML `GET` request in the Dashboard may cause slow page load times.

For instance at Utah the home directory can be "notice-ably" slow at times. So keeping the scans to a single route may be better in the long run.

**Comment by ericfranz** [comment]
Not focusing on developer dashboard right now.
