### ISSUE TITLE
Add AppConfig object and app development and app sharing flags

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-dashboard#236]
In the dashboard we need a central place to store dashboard app specific configuration. This is domain configuration (i.e. whether app development is enabled or not, whether certain special URLs are set, etc.).

Currently these environment variables are just used throughout the app instead of being used to set configuration options in a central place. Similar to how we do in gems, we need a namespace for domain specific configuration, preferably separate from the Rails.application.configuration object.

While there are plenty of "examples" and "tutorials" on adding more config options to Rails.application.configuration i.e. Rails.application.configuration.x.xyz this is not good for two reasons:

1. the configuration options that can be set are not defined anywhere (a separate config class would define these as methods on the class)
2. custom Rails.application.configuration options are typically set on initializers, meaning we would have to ensure that our creation of these configuration options (with sensible defaults) occurred prior to other initializers that want to override these, or would have to occur after to ensure that we don't override custom values

Given this it makes the most sense we just have our own config object. However, if/when we do this we should be careful. Doing something like we do in NavConfig, where we set default values during class initialization, instead of returning default values lazily when methods are called, can result in these default values being re-set when Rails reloads the class in development mode. In other words: https://github.com/OSC/ood-dashboard/blob/ca4864b044f24b313b05f38a1fa3a6bb3249584c/app/apps/nav_config.rb#L6-L7 is re run every time code in this file is modified, but any initializers that set these values would not be rerun.

**Comment by ericfranz** [comment]
Also we might want to think of a good name so we don't confuse this with Rails.application.configuration...

I'm not sure if AppConfig is sufficient.

**Comment by nickjer** [comment]
I am fine with an app-specific configuration object, especially since I would like to move away from `.env.local` (using environment variables) and instead to a global app configuration file, e.g., `/etc/ood/config/apps/dashboard.yml.erb` (or something similar).

One possibility is...

The object can be defined in `config/configuration.rb` (this won't be reloaded by Rails). And we can add it inside of `config/environment.rb` as:

```ruby
# Load the Rails application.
require File.expand_path('../application', __FILE__)

# Load the application configuration.
require File.expand_path('../configuration', __FILE__)

# Initialize the Rails application.
Rails.application.initialize!
```

Then you can take advantage of it within the initializers.

**Comment by ericfranz** [comment]
@nickjer good suggestion. PR created.
