### ISSUE TITLE
Navbar changes when an error is displayed

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-dashboard#25]
Before error...

![image](https://cloud.githubusercontent.com/assets/4260509/19225153/f6143aea-8e63-11e6-85f4-cd0d1d752268.png)

During error...

![image](https://cloud.githubusercontent.com/assets/4260509/19225156/0626d118-8e64-11e6-933d-3378c99aafc6.png)

**Comment by ericfranz** [comment]
Ha that was intentional. I guess maybe that scares people and I should remove it.

The rationale was that if a crash occurs, and you provide a custom error handler, you want as little code to run for that custom error handler because you don't want that code to also throw an exception.

**Comment by ericfranz** [comment]
https://github.com/OSC/ood-dashboard/pull/67 ensures one layout is used for everything:

![screen shot 2016-11-08 at 2 44 11 pm](https://cloud.githubusercontent.com/assets/512333/20114336/dae89d72-a5c1-11e6-86cc-6ac344b1e12f.png)
