### ISSUE TITLE
App Development - Bug in asset precompilation

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-dashboard#250]
When I precompile assets via the developer sandbox, the asset path that is defined is the path to the dashboard asset path, rather than the app asset path. There may be some environment variable responsible for this due to the fact that the precompilation step takes place within the dashboard process.

![asset precomp](https://user-images.githubusercontent.com/2374718/30390372-e3e1e252-9883-11e7-823e-466b39115aef.png)

Steps to reproduce:

- Add an `asset_path` tag to a precompile resource. [(Example)](https://github.com/OSC/weld-predictor/blob/master/app/assets/javascripts/render_three_shape.js.erb#L45)
- Precompile the assets from within the awesim dashboard.
- Load application and note the dashboard asset path is baked into the precompiled js (see image)

**Comment by ericfranz** [comment]
@brianmcmichael can you confirm that this is related to https://github.com/OSC/ood-dashboard/issues/127?

**Comment by brianmcmichael** [comment]
I'm not sure how to confirm this but I would make an educated guess that it's related.

**Comment by ericfranz** [comment]
Not focusing on developer dashboard right now.
