### ISSUE TITLE
Developer documentation link appears even when there is no valid link configured

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-dashboard#255]
https://github.com/OSC/ood-dashboard/blob/a65d101b1e339d3644a764935dedf301faf9be77/app/views/layouts/nav/_develop_dropdown.html.erb#L7

Should replace with something like:

```
<%= nav_link("Developer Documentation", "book", developer_docs_url) %>
```

**Comment by ericfranz** [comment]
And optionally provide a default value for the URL to be the Development section in https://osc.github.io/ood-documentation/master/.

**Comment by nickjer** [comment]
Should the Dashboard know which version of OOD is installed? So that it points to the corresponding Developer Documentation?

**Comment by ericfranz** [comment]
Should we default this to https://osc.github.io/ood-documentation/master/app-development.html? Or better yet https://go.osu.edu/ood-app-dev so we can change the URL at a later time?

**Comment by nickjer** [comment]
I wouldn't recommend this as this would require us to keep the developer documentation in the `master` branch backwards compatible with every version of OOD that links to it.

I lean more towards having the default link point to a specific version of the developer documentation. And keeping this link in sync with whatever version of OOD the Dashboard goes out with.

**Comment by ericfranz** [comment]
>I lean more towards having the default link point to a specific version of the developer documentation. And keeping this link in sync with whatever version of OOD the Dashboard goes out with.

The drawbacks for this:

1. changes that would benefit everybody, or a significant change in location of developer documentation would not be handled
2. require remembering to update URL every time we deploy a new version of OOD 

Lets start with https://go.osu.edu/ood-app-dev and then we can re-address later when we have a packaging solution.

> keep the developer documentation in the master branch backwards compatible with every version of OOD that links to it

I think for this right now we can just call out that certain features were introduced in certain versions. The entire app development documentation needs a complete reorganization.
