### ISSUE TITLE
Add feature flag to enable/disable FACLs interface on shared apps

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-dashboard#270]
Before we document app sharing for everyone, we should add a feature flag to disable/enable the FACLs interface on shared apps, which currently only works for NFS4 FACLS. Later we could provide the ability to enable NFS3 or 4 as appropriate.

The default would be "disabled".

Also, when this feature is enabled, consider applying default access permissions for newly created shared app directory to be 750, in the new process.

- 750 would benefit AweSim when this feature is enabled
- 755 would benefit OSC when this feature is disabled and per group app sharing is allowed

**Comment by ericfranz** [comment]
The default would be "disabled".

**Comment by ericfranz** [comment]
Also, when this feature is enabled, consider applying default access permissions for newly created shared app directory to be 750, in the new process.

- 750 would benefit AweSim when this feature is enabled
- 755 would benefit OSC when this feature is disabled and per group app sharing is allowed

**Comment by ericfranz** [comment]
This adds it: 8f2c5ed9f925a6fb1eee8e6d29695b103c2e8e48
But it is a temporary solution. We should revisit later. Might be good enough for now.

**Comment by nickjer** [comment]
@ericfranz should we close this since the feature flag was already added?

**Comment by ericfranz** [comment]
Yeah. We'll open other issues when the time comes (if it comes) to support both NSF3&4 FACLs in Open OnDemand.
