### ISSUE TITLE
Consider adding a title to the top of interactive sessions

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-dashboard#278]
The pages that display the forms used for launching interactive sessions (left) look very similar. The user has to either look to the bottom left of the page (not intuitive), or to the paragraph text (cumbersome) to orient themselves.

It might be helpful to add a title to the top of the form (see example, right) so that users can see at a glance what form they are looking at.

![title](https://user-images.githubusercontent.com/2374718/31948864-eb5c28f2-b8a5-11e7-994e-4825b25e3ab9.png)

**Comment by ericfranz** [comment]
Or put the title and description pulled to the right using the trick that was used for subapps when we displayed those in a separate pane on right.
