### ISSUE TITLE
Add root route helpers to batch connect apps

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-dashboard#288]
When accessing batch connect apps via the dashboard, it is necessary that `session_contexts/new` be appended after the app name to access the page. We should consider adding route helpers to the dashboard so that if the user attempts to access the URL without `new` or without `session_contexts/new` they are redirected to the appropriate route, rather than seeing the "Not Found" page.

![1](https://user-images.githubusercontent.com/2374718/33721019-b5854bd6-db33-11e7-892d-fc2cae4c12a7.PNG)
![2](https://user-images.githubusercontent.com/2374718/33721023-b82524ba-db33-11e7-81f1-46291eef9d75.PNG)
![3](https://user-images.githubusercontent.com/2374718/33721025-ba0d5540-db33-11e7-9676-d3d51d60d781.PNG)

**Comment by nickjer** [comment]
This is a copy of https://github.com/OSC/ood-dashboard/issues/283
