### ISSUE TITLE
App Development: "bundle install" assumes "bin/bundle"

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-dashboard#290]
Working on PSC I discovered that the "bundle install" button has "bin/bundle" assumed in the command.

After cloning the [OSC/ood-example-ps](https://github.com/OSC/ood-example-ps) app, which is a simple rack app, the dashboard properly recognizes the app as a "Passenger Rack App", however, when I attempt to install the gems specified in the repository via the "bundle install" button, I am presented with an error (see below) because `bin/bundle` is not present.

![untitled2](https://user-images.githubusercontent.com/2374718/33997731-51860de8-e0b3-11e7-8109-ad75ced54add.png)

![untitled](https://user-images.githubusercontent.com/2374718/33997728-4f0a4cfa-e0b3-11e7-888f-609d96cea365.png)

I can not switch over to the shell and enter these commands manually because the default cluster is different than the ondemand node, and the required SCL packages are not available. Building gems outside of the host environment could also present potential issues in the future, if not necessarily in this case.

The simplest solution would probably be to fall back to the bundle version provided by `rh-ruby22` in the event that `bin/bundle` is unavailable, but the team may be able to think up a more robust solution.

**Comment by nickjer** [comment]
We should probably avoid using `bin/bundle` as Passenger doesn't use it when launching the app:

https://www.phusionpassenger.com/library/indepth/ruby/bundler.html

It seems Passenger will just use whatever Bundler tool is installed in the Ruby that Passenger runs under (which in our case is Software Collections `rh-ruby22`).

So maybe the simplest solution is just to always call `bundle ...` as opposed to `bin/bundle ...`?
