### ISSUE TITLE
Keep noVNC up-to-date

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-dashboard#297]
Need to check if there is a noVNC update and if it will work with our current code.

**Comment by ericfranz** [comment]
Maybe we can write an automated test that checks the latest stable release git version and compares it to the one we have?

**Comment by nickjer** [comment]
Unfortunately the latest stable release was back in January and we have been deploying latest `master` branch commits.

**Comment by nickjer** [comment]
But maybe an automated tool that pulls down the latest commit and builds it under `public/noVNC-<SHA>` for testing and possible deployment.

**Comment by ericfranz** [comment]
Hmm. We don't want an automated test for new versions to fail every time noVNC devs commit to master. We also want to be able to make the decision whether or not to install a new version, so if there was an automated tool to pull down the latest commit, that would still need to be something we manually choose to execute.

Maybe an automated test would compare the time span between the commit we are using and the latest commit to noVNC, and if that diff is > 3 months the test fails? But then we would want a way to say "no, that commit is no good, lets wait till they work some more".

**Comment by ericfranz** [comment]
Maybe the simple solution is we maintain a checklist in the wiki for "check for updates to dependencies" that we walk through once a month.

**Comment by nickjer** [comment]
noVNC 1.0.0 was just released. Now would be a good time to update it.
