### ISSUE TITLE
Developer documentation crash

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-dashboard#30]
Clicking the link for Developer Documentation...

![image](https://cloud.githubusercontent.com/assets/4260509/19392434/c4ab5364-91fe-11e6-8df3-52c93baafd5b.png)

crashes with error...

![image](https://cloud.githubusercontent.com/assets/4260509/19392427/b7fecf74-91fe-11e6-97f0-b591be389a5e.png)

**Comment by ericfranz** [comment]
https://github.com/OSC/ood-dashboard/pull/32
