### ISSUE TITLE
don't open every app in a new window, keep them in the same window

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-dashboard#326]
Community request:

don't open every app in a new window, keep them in the same window

**Comment by brianmcmichael** [comment]
Note:

This was a deliberate design decision. OnDemand-branded apps open in the same tab, non-branded apps (file explorer, shell, editor, etc.) open in new tabs.

**Comment by ericfranz** [comment]
duplicate of https://github.com/OSC/ood-dashboard/issues/430
