### ISSUE TITLE
Apache should handle logout at /logout

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-dashboard#34]
1. Replaces hack introduced in https://github.com/OSC/ood-dashboard/issues/31
2. This can handle stopping the PUN when the user logs out

**Comment by nickjer** [comment]
Maybe this should be moved to `ood-portal-generator` and have Trey added to the discussion. Also, could you post your current solutions for logging out of OIDC and Shibboleth?

**Comment by ericfranz** [comment]
Moved to https://github.com/OSC/ood-portal-generator/issues/6
