### ISSUE TITLE
Upgrade Font Awesome to 5

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-dashboard#341]
Font Awesome is now up to version 5, and the SASS gem has recently been updated as well:

https://github.com/FortAwesome/font-awesome-sass

This does introduce some breaking changes as some of the icon names have changed and there is a new icon style that needs to be specified *solid*, *regular*, and *brands*.

**Comment by ericfranz** [comment]
See https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4#shims for backwards compatibility. Though the modifications required don't seem that many. And Font Awesome 5 supports the prefix "fa" like before.

**Comment by ericfranz** [comment]
When we do this we will want to change the myjobs icon to be fa-list instead of tasks whose icon has changed.

**Comment by laser505t** [comment]
fa-list is the icon used by My Interactive Sessions. Maybe confusing?

**Comment by ericfranz** [comment]
Do you have an alternative suggestion? It is a “list of active seasons”.

That said I don’t expect we would find any icon that would be “self evident” to beginners and imho icons without text are meant for “intermediate users” who by that time learn which icons associate with which actions or pages. By the time you made the association it doesn’t matter what the icon is.

**Comment by laser505t** [comment]
![image](https://user-images.githubusercontent.com/38962417/43212548-38e32934-9002-11e8-871f-0714f42582a9.png)
"magic" (fas) icon for job composer and "window-restore" (far) icon for interactive sessions?
