### ISSUE TITLE
Sticky Footer broken in IE11

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-dashboard#347]
Sticky footer is broken in IE11

![untitled2](https://user-images.githubusercontent.com/2374718/37216840-d79f171c-2389-11e8-868b-0f031267b221.png)

**Comment by nickjer** [comment]
It seems it is still broken, but now it doesn't go to the bottom of the page if the content is very long.

![image](https://user-images.githubusercontent.com/4260509/37988890-11d7c61e-31d0-11e8-9e80-d3b468aa7aa3.png)

**Comment by nickjer** [comment]
Moved this to issue #351
