### ISSUE TITLE
Add special system tests for testing job configuration

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-dashboard#358]
To address feedback mentioned in https://github.com/OSC/Open-OnDemand/issues/33

Several approaches to this.

1. Add tests to test/system/* and ensure they can be executed in isolation from other tests. See Rails 5 conventions which now have integrated system testing support so we don't deviate. Use normal assertions but print extra detailed information when a failure occurs. Consider printing extra information when all tests pass.

2. Add a separate Rake task that will generate a report based on the "test jobs/actions" it takes.

In both cases, we want to:

1. add a test to submit a short job, verify it was submitted, appears in the queue, and that it outputs an expected result value
2. add a test to get a status of all the running jobs and verify that the count is > 0 and certain values that all adapters will return are populated with non-null data
3. display a report listing all of the configured clusters, their job adapter configuration if it exist, and what associated adapter is being used, and any other helpful information
4. document running this test in our documentation after configuring OnDemand cluster config with job adapter configuration

If there is a failure, we might want to provide recommendation on how to ask for installation help by sharing this report and any other relevant information.

**Comment by ericfranz** [comment]
Maybe instead of `test/system/*` we could do `test/install/*`. Though while Rails 5 system tests uses Capybara, storing the tests in the test/system directory is just the convention, as Rails 5 system tests actually subclass ApplicationSystemTestCase (http://guides.rubyonrails.org/testing.html#system-testing). I don't believe a normal test case in this directory will be run by a Selenium driver.

**Comment by ericfranz** [comment]
>By default, running bin/rails test won't run your system tests. Make sure to run bin/rails test:system to actually run them.

**Comment by ericfranz** [comment]
Rake task(s) will be added/auto-generated for each properly configured cluster, with a default task that will run all the cluster specific tasks and exist even if cluster config does not. For example, at OSC we have:

```
$ ls -1 /etc/ood/config/clusters.d/
.
..
oakley.yml
owens.yml
quick.yml
ruby.yml
```

So the rake tasks would be:

```
$ bin/rake -T
...
rake test:jobs                          # Test job config for each cluster
rake test:jobs:oakley                   # Test job config for oakley
rake test:jobs:owens                    # Test job config for owens
rake test:jobs:quick                    # Test job config for quick
rake test:jobs:ruby                     # Test job config for ruby
```

And be executed like:

```
RAILS_ENV=production bin/rake verify:jobs # test all
RAILS_ENV=production bin/rake verify:jobs:owens # test owens
```

#### 1. Submit test

The rake task will submit a job, verify it is queued, runs, and then produces desired output. It will loop and check the status, letting user know.

Default `OodCore` script:

```
dir = Dir.mktmpdir(nil, Configuration.dataroot.join("tmp").tap {|t| t.mkpath }.to_s)
out = File.join dir, "output.txt"
Script.new(output_path: out, content: 'echo "Hello World"', shell_path: '/bin/bash')

# 1. now submit, check status and sleep in a loop till the job is done
#    letting user know when each status check occurs
# 2. verify out contains Hello World		
# 3. delete dir and out (no recursive delete just to be safe)
```

If `SUBMIT_ARGS` env is set we will do this:

```
require 'shellwords'
Script.new(job_name: "test:jobs:owens", output_path: out, content: 'echo "Hello World"', shell_path: '/bin/bash', native: Shellwords.split(ENV['SUBMIT_ARGS']))
```

So you can supply custom native submission arguments for the clusters:

```
SUBMIT_ARGS='-A PZS0530 -l nodes=1:ppn=1'  RAILS_ENV=production bin/rake verify:jobs:owens
```

* note - we will need to update pbs-ruby and the torque adapter to accept arrays for the native attribute

#### 2. Status test

The rake task will also check status of all jobs, verify no error was created, and that jobs are > 0 and that jobs that returned contain non-null items, and display output of up to 5 jobs from the list.

**Comment by ericfranz** [comment]
A user running this as a rake task would be partially helpful, as the config could be verified as soon as the dashboard code was on the system i.e. right after installing the OnDemand rpm work could begin on the /etc/config cluster config.

However, ultimately this would also need to be an endpoint on the dashboard, i.e. `/pun/sys/dashboard/install` where it helps you verify the installation and configuration.

In light of this, should the rake task be called `test:jobs` or `test:install:jobs` or `test:install`?

**Comment by ericfranz** [comment]
Steps:

1. build rake task
2. extract code into class
3. use class in endpoint `/pun/sys/dashboard/install` to enable the same type of verification => note that since this is potentially a long running request, will need to do something clever to ensure the request doesn't prematurely get killed, OR in this case store state for a test...

**Comment by ericfranz** [comment]
Maybe when running this we can recommend users do something like:

    env -i HOME="$HOME" PATH="$PATH" USER="$USER" scl enable rh-ruby22 -- RAILS_ENV=production bin/rake test:jobs

Or we don't wipe the login shell environment. We just say that this test is not 100% replacement for actual testing through the web app itself.

A stateless that runs for possibly minutes is easy to do from the command line and more difficult to do from a webpage.

I think an MVP for JOSS would be this rake task with directions on using it to verify an install in the release documentation. And we could open issues for enhancing this with a /install webpage in the future.

**Comment by nickjer** [comment]
Another issue with rake tasks is that the user *in most cases* will need to `cd` into the Dashboard app to run the Rake task. Also if you intend on the tests running asynchronously in a web app, then utilizing JobComposer with its Templates may be best.

If this is just to test cluster configs, maybe a simple Ruby CLI using Thor (e.g. `/opt/ood/tests/test_clusters`) would be better. Something like:

```console
$ /opt/ood/tests/test_clusters list
owens
oakley
ruby
$ /opt/ood/tests/test_clusters simple_test owens
Submitting 'simple_test' to 'owens'...
Got job id 1832983.
Waiting for job to run...
Waiting for job to run...
Finished.
✓ All tests passed!
$ /opt/ood/tests/test_clusters lint all
Checking 'owens'...
✓ Passed!
Checking 'oakley'...
Missing title! Please provide the following in the Oakley cluster config:
    metadata:
      title: <Title goes here>
✗ Failed!
Checking 'ruby'...
✓ Passed!
```

**Comment by nickjer** [comment]
Will throw together a quick rake task for now and hold off on a full design for later.
