### ISSUE TITLE
Potential problem if OOD_ANNOUNCEMENT_PATH is set

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-dashboard#365]
See https://github.com/OSC/ood-dashboard/blob/93193c10d9dedf8c5d3580709196f3a840465d98/config/configuration_singleton.rb#L51-L61

It seems like this would be more desirable:

```ruby
  def announcement_path
    [
      ENV["OOD_ANNOUNCEMENT_PATH"],
      "/etc/ood/config/announcement.md",
      "/etc/ood/config/announcement.yml",
      "/etc/ood/config/announcements.d"
    ].compact.map {|p| Pathname.new(p)}
  end
```

I remember having a discussion about this, but I do not remember what we discussed.

**Comment by ericfranz** [comment]
Also, we should probably add "/etc/ood/config/announcement.yaml" as an option too, so we don't trip people up with the yml extension.

**Comment by nickjer** [comment]
I have the environment variable `OOD_ANNOUNCEMENT_PATH` override the default paths much like `OOD_CLUSTERS` overrides `/etc/ood/config/clusters.d`. Otherwise there would be no way to override the default announcement path aside from monkey patching.

**Comment by nickjer** [comment]
I think we should definitely open an issue about treating `*.yaml` the same as `*.yml`. As this affects more than just announcements since we use them through out Interactive Apps and for building general app objects with the `manifest.yml`.

**Comment by ericfranz** [comment]
Taking Jeremy's advice and not doing.
