### ISSUE TITLE
App links in developer sandbox for Shell app link to sys version

### ISSUE THREAD

**Issue by laser505t** [OSC/ood-dashboard#399]
There is special code for creating links for the shell app, which does what we want in the top menu. But in the developer sandbox the same URLs are used:
![image](https://user-images.githubusercontent.com/38962417/44743324-2d9d4080-aad0-11e8-8db9-dc7dbd98946e.png)
So clicking one of these does not open the developer's sandboxed version, but the system version, which is horrible, especially when you don't pay attention to the URL and wonder why nothing is changing :(
The special code is here: https://github.com/OSC/ood-dashboard/blob/4b7b7f77caafb184de25fdb69250e1813342d6b9/app/apps/ood_app.rb#L82-L111
And consequentially, this would affect someone developing the file explorer app, because both rely on OodAppkit.xxx.url(). See directly above the shown snippet.

**Comment by ericfranz** [comment]
Instead of `OodAppkit.shell.url` this could probably be replaced with something like:

```ruby
OodAppkit::Urls::Shell.new(base_url: app_path(name, type, owner)).url(host: cluster.login.host)
```

Similarly with the Files URL. Also this long method could be refactored into something far simpler, like shell_urls, files_urls as methods.
