### ISSUE TITLE
Add a lint warning if there are migrations that need run (to sandbox apps)

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-dashboard#41]

**Comment by nickjer** [comment]
Do rails apps not run if there are outstanding migrations? I haven't tested this. Also, I could see cases where a developer may want to rollback a migration for testing.

Maybe this should be a lint error for just a missing database?

**Comment by brianmcmichael** [comment]
> Do rails apps not run if there are outstanding migrations?

No. They don't, and in development they return an error that migrations are pending.

The user will just see our nondescript error page in production, though, so the only way to tell will be the logs. Keep this.

**Comment by nickjer** [comment]
This may be too difficult to do as I'd have to run rails to determine the database that will be accessed. In production we'd just check the environment variable `DATABASE_URL`.

**Comment by ericfranz** [comment]
Lets not do this. Usually if there are pending migrations the error page tells the user what commands to run.
