### ISSUE TITLE
Ability to change dashboard text

### ISSUE THREAD

**Issue by jeremypmann** [OSC/ood-dashboard#423]
On the main page of the dashboard is there a way to replace the Open OnDemand logo and text beneath it?

**Comment by ericfranz** [comment]
You can change the logo by setting OOD_DASHBOARD_LOGO in an env file at /etc/ood/config/apps/dashboard/env. Here is an example:

https://github.com/OSC/osc-ood-config/blob/8e8fd855de211826c66f78b73075d265bf0c98d8/ondemand.osc.edu/apps/dashboard/env#L4

For changing the text, that isn't possible yet, but that will be available in OOD 1.5 via the ability to add localization files to /etc/ood/config. Until then, you could modify the file directly if you wanted to achieve the desired result. In a 1.3 installation the file to modify is here:

/var/www/ood/apps/sys/dashboard/app/views/dashboard/index.html.erb

You can see the text:

    <p class="lead">OnDemand provides an integrated, single access point for all of your HPC resources.</p>

**Comment by MorganRodgers** [comment]
While you cannot change the 'OnDemand provides...' text you *can* display a message of the day and announcements.

Two hooks for customizing the dashboard are announcements and motd. Announcements get the classes alert alert-warning and appear above the OOD_DASHBOARD_LOGO . Announcement files are expected to be found at: /etc/ood/config/announcements.(md|yml) . To display a motd file on the dashboard ensure that the file /etc/ood/config/apps/dashboard/env exists at minimum with the following content:

```bash
MOTD_PATH="/path/to/your/motd" # this supports a few different URI options including RSS feeds
MOTD_FORMAT="$MOTD_FORMAT_HERE" # markdown, txt, rss
```

More complex behavior is possible and is detailed at: https://github.com/OSC/ood-dashboard/tree/master/config/examples and a more complete env file is available here: https://github.com/OSC/ood-dashboard/blob/master/config/examples/osc/env

**Comment by jeremypmann** [comment]
Perfect, thanks!



Jeremy Mann
Enterprise Research Solutions Engineer
Research Computing Support
The University of Texas at San Antonio
(210) 458-4074
Jeremy.Mann@utsa.edu<mailto:Jeremy.Mann@utsa.edu>

[LOGO]

Not satisfied with the service you’re receiving? LET’S TALK! I’m open to all comments and suggestions.  Also, feel free to contact my manager Brent League 458-5877.  We want to give you the best experience in Research Technology.

**Comment by MorganRodgers** [comment]
@jeremypmann note that I got the options for announcements incorrect in my comment. I have updated the original to display the correct paths.
