### ISSUE TITLE
Make a lint check for missing assets when building Shared Apps

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-dashboard#43]
1. Obviously if no assets at all have been built, it is a problem. A simple search for any directory with "any" assets would be helpful.
2. When building assets, is there some way we can determine the git hash that was used? Or somehow detect that the built assets were done from those src assets? This is more difficult. 

The first could obviate the need for the second, which could be a future FR.

**Comment by nickjer** [comment]
First will be easy to implement.

**Comment by nickjer** [comment]
After a quick google search, I could not find any easy to implement solution for the second feature request. So I am going to push back on it.
