### ISSUE TITLE
For Shared Apps, add a new button called "Rebuild App" that does Bundle Install, Rebuild Assets, and Restart App

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-dashboard#46]
_I copied this description from the conversation below, then updated it accordningly._

https://github.com/OSC/ood-dashboard/blob/3080b871f93c7413d528beff02587652fb2d4ec5/app/controllers/products_controller.rb#L110-L115

Add a new command:

```
rebuild_passenger_rails_app: [{"HOME" => "", "RAILS_ENV" => "production"}, "bin/bundle install --path=vendor/bundle && bin/rake assets:clobber && bin/rake assets:precompile && bin/rake tmp:clear && mkdir -p tmp && touch tmp/restart.txt && echo 'Done!'"]
```

And a button after https://github.com/OSC/ood-dashboard/blob/3080b871f93c7413d528beff02587652fb2d4ec5/app/views/products/show.html.erb#L47

`Rebuild App` should be the title of the button and make it the bootstrap "primary" color? Bonus: tooltip should indicate it does all three of the other buttons actions in a row: Bundle Install, Rebuild Assets, and Restart App

Show only `if @type == :usr && @product.passenger_rails_app?`

See below for conversation regarding how we got here.

Original issue description was something like:

>For Shared Apps add Update App button that does that does Bundle Install, Rebuild Assets, and Restart App

**Comment by nickjer** [comment]
Is this called "Update App" for dev apps as well?

**Comment by ericfranz** [comment]
I'd just do it for shared apps, because shared apps its always: fetch/checkout tag/update

But that isn't the case with dev apps

**Comment by ericfranz** [comment]
https://github.com/OSC/ood-dashboard/blob/3080b871f93c7413d528beff02587652fb2d4ec5/app/controllers/products_controller.rb#L110-L115

Add a new command:

```
update_app: [{"HOME" => "", "RAILS_ENV" => "production"}, "bin/bundle install --path=vendor/bundle && bin/rake assets:clobber && bin/rake assets:precompile && bin/rake tmp:clear && mkdir -p tmp && touch tmp/restart.txt && echo 'Done!'"]
```

And a button after https://github.com/OSC/ood-dashboard/blob/3080b871f93c7413d528beff02587652fb2d4ec5/app/views/products/show.html.erb#L47

A better name than `update_app`? Maybe the button should be: "Bundle Install & Precompile Assets & Restart App" or maybe just "Update App" and make it primary color but then add a tooltip that explains that it does all three (Bundle Install, Precompile, Assets, and Restart App).

Show only `if @type == :usr && @product.passenger_rails_app?`

**Comment by ericfranz** [comment]
@nickjer any objections for proposed solution?

**Comment by nickjer** [comment]
Naming suggestions:

`update_app` => `rebuild_passenger_rails_app`
"Update App" => "Rebuild Rails App"

other choices: `rebuild/build/redeploy/deploy/stage/restage/compile/recompile`

As I'd be hesitant to call it "Update" if you aren't actually updating the app's code (i.e., `git fetch` & `git checkout`), but instead are re-building the app.

Also, you will need to develop the single line command that includes `scl enable ...` that works in an environment without `scl`.

**Comment by ericfranz** [comment]
I like the title "Rebuild App" and the key "rebuild_passenger_rails_app"

**Comment by ericfranz** [comment]
The "command" that is displayed to the user for the restart button is an example of how to show the user using scl and running multiple commands at once.

**Comment by brianmcmichael** [comment]
#111 merged.
