### ISSUE TITLE
Add a lint check in case that `require: 'dotenv/rails-now'` is not included in the Gemfile

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-dashboard#47]
We do this:

```
gem 'dotenv-rails', '~> 2.1.1', require: 'dotenv/rails-now'
```

So that we ensure that rake tasks have the dot env files loaded immediately so RAILS_RELATIVE_URL_ROOT is set when building assets. If this does not exist, then RAILS_RELATIVE_URL_ROOT will not be properly set, and the user will run into problems.

This is possibly an easy thing to overlook, though for new apps using the generator this will already be set.

Using a regex against the Gemfile probably is not the best approach. Before proceeding, post the planned implementation and solicit feedback.

**Comment by nickjer** [comment]
Another solution for this is that the Dashboard sets the env var RAILS_RELATIVE_URL_ROOT when building assets. I believe it has this information from the app Routers.
