### ISSUE TITLE
Launch button for interactive apps have the incorrect title

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-dashboard#473]
Most of the buttons have "Batch Connect Sessions Novnc Launch" which is not a good replacement for "Launch NoVNC". We will want to fix this and push a change quickly (if it doesn't get in today that's okay since it is a cosmetic defect).

![screen 2019-05-21 at 11 57 27 AM](https://user-images.githubusercontent.com/512333/58111542-a5ac1900-7bbf-11e9-8cbd-4faff2e0ac33.png)

**Comment by ericfranz** [comment]
This is the PR that introduced this defect: https://github.com/OSC/ood-dashboard/pull/455

**Comment by ericfranz** [comment]
No actually that PR was good. The defect was introduced here:

https://github.com/OSC/ood-dashboard/commit/083d2504877bdf4255e04b0ee8ecbace3530729c#diff-1a0752f915bf78c230b5f457fe0bfadb

The translation is incorrect, and the translation should accept an argument for the name of the app.

**Comment by MorganRodgers** [comment]
Fixed in 5a76eca376d438cff9d0c85f578582ae7c13d8c3.
