### ISSUE TITLE
Add polyfill for URLSearchParams and add browser compatibility for IE11?

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-dashboard#479]
A polyfill for URLSearchParams would enable earlier versions of Edge to be used and may open back the possibility for supporting IE along with Edge.

**Comment by MorganRodgers** [comment]
https://github.com/ungap/url-search-params appears to the way to go at the moment.

**Comment by MorganRodgers** [comment]
Was added in https://github.com/OSC/ood-dashboard/pull/480.
