### ISSUE TITLE
Install dashboard failed

### ISSUE THREAD

**Issue by superdavidxp** [OSC/ood-dashboard#484]
I tried to install dashboard but failed with following error message

`cd /home/hal9000/dashboard

== Building Dashboard App ==
RAILS_ENV               = production
RAILS_RELATIVE_URL_ROOT = /pun/sys/dashboard

== Compiling assets ==
bin/rake assets:clobber
rake aborted!
Psych::SyntaxError: (<unknown>): did not find expected '-' indicator while parsing a block collection at line 18 column 5
/home/hal9000/dashboard/vendor/bundle/ruby/2.4.0/gems/ood_core-0.8.0/lib/ood_core/clusters.rb:31:in `block (2 levels) in load_file'
/home/hal9000/dashboard/vendor/bundle/ruby/2.4.0/gems/ood_core-0.8.0/lib/ood_core/clusters.rb:30:in `any?'
/home/hal9000/dashboard/vendor/bundle/ruby/2.4.0/gems/ood_core-0.8.0/lib/ood_core/clusters.rb:30:in `block in load_file'
/home/hal9000/dashboard/vendor/bundle/ruby/2.4.0/gems/ood_core-0.8.0/lib/ood_core/clusters.rb:29:in `each'
/home/hal9000/dashboard/vendor/bundle/ruby/2.4.0/gems/ood_core-0.8.0/lib/ood_core/clusters.rb:29:in `load_file'
/home/hal9000/dashboard/vendor/bundle/ruby/2.4.0/gems/ood_appkit-1.0.3/lib/ood_appkit/configuration.rb:128:in `parse_clusters'
/home/hal9000/dashboard/vendor/bundle/ruby/2.4.0/gems/ood_appkit-1.0.3/lib/ood_appkit/configuration.rb:18:in `clusters'
/home/hal9000/dashboard/lib/tasks/test.rake:7:in `block (2 levels) in <top (required)>'
/home/hal9000/dashboard/lib/tasks/test.rake:2:in `block in <top (required)>'
/home/hal9000/dashboard/lib/tasks/test.rake:1:in `<top (required)>'
/home/hal9000/dashboard/vendor/bundle/ruby/2.4.0/gems/railties-4.2.11/lib/rails/engine.rb:658:in `load'
/home/hal9000/dashboard/vendor/bundle/ruby/2.4.0/gems/railties-4.2.11/lib/rails/engine.rb:658:in `block in run_tasks_blocks'
/home/hal9000/dashboard/vendor/bundle/ruby/2.4.0/gems/railties-4.2.11/lib/rails/engine.rb:658:in `each'
/home/hal9000/dashboard/vendor/bundle/ruby/2.4.0/gems/railties-4.2.11/lib/rails/engine.rb:658:in `run_tasks_blocks'
/home/hal9000/dashboard/vendor/bundle/ruby/2.4.0/gems/railties-4.2.11/lib/rails/application.rb:452:in `run_tasks_blocks'
/home/hal9000/dashboard/vendor/bundle/ruby/2.4.0/gems/railties-4.2.11/lib/rails/engine.rb:453:in `load_tasks'
/home/hal9000/dashboard/Rakefile:6:in `<top (required)>'
(See full trace by running task with --trace)
/opt/rh/rh-ruby24/root/usr/share/gems/gems/rake-12.0.0/lib/rake/file_utils.rb:66:in `block in create_shell_runner': Command failed with status (1): [bin/rake assets:clobber...] (RuntimeError)
	from /opt/rh/rh-ruby24/root/usr/share/gems/gems/rake-12.0.0/lib/rake/file_utils.rb:56:in `sh'
	from bin/setup:52:in `block in <main>'
	from /opt/rh/rh-ruby24/root/usr/share/ruby/fileutils.rb:120:in `chdir'
	from /opt/rh/rh-ruby24/root/usr/share/ruby/fileutils.rb:120:in `cd'
	from /opt/rh/rh-ruby24/root/usr/share/gems/gems/rake-12.0.0/lib/rake/file_utils_ext.rb:37:in `chdir'
	from bin/setup:36:in `<main>'`

**Comment by johrstrom** [comment]
This seems to have erred out while trying to load your cluster config yml. Specifically it not find expected `-` character.

Look at line 18 column 5 of your cluster config, there seems to be something wrong with it?  You can link it here if you need.

**Comment by ericfranz** [comment]
@johrstrom building the dashboard should not require the cluster config. I'd open a separate bug issue here if you can reproduce by creating a bad cluster config and then trying to build the app.

**Comment by johrstrom** [comment]
I can reproduce even on a live system. In this example, he's installing a new dashboard (under say dev), but I can even trigger a similar error when you misconfigure a file in `/etc/ood/config/clusters.d/` and the PUN boots. 

But, it is an error originaaing in the ood core library, so I'll open a ticket against it. It should just eat the error, spitting it out to logs, then move on. It shouldn't crash the dashboard.

**Comment by johrstrom** [comment]
https://github.com/OSC/ood_core/issues/150 created

**Comment by ericfranz** [comment]
So there are actually three separate problems here:

1. When building the Dashboard app, the cluster configs were loaded (because presumably OodAppkit.clusters was called). This should not happen.
2. When reading the cluster configs, an exception was raised that was not a well-formatted message. If the message was well formatted (i.e. a custom one we wrote) it likely would have told @superdavidxp enough information to solve his problem. Of course if 1. the error won't occur in this context.
3. When reading the cluster configs, an unhandled exception is raised. Ideally, we have a better user experience. For example, the app starts without failing and an error message displays. Or there is an install page on OnDemand that shows the broken cluster configs and how to fix them.

The first two should be fixed immediately. The third is more expensive, requires some design, and affects

**Comment by ericfranz** [comment]
Well based on my comment on the ood_core issue, 2. and 3. might be easier fixed than I thought.

**Comment by superdavidxp** [comment]
@ericfranz, Thank you for your advice, I have found the format error with my cluster_config.yaml.
