### ISSUE TITLE
Should we display a warning if "A::EVERYONE@:rxtncy"

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-dashboard#49]
1. I set permission on my app directory to 755 (`cd ~/awesim/share/cfs && chmod 750 .`)
2. Now everyone in the awesim group can access my app (because ~ is 755 and ~/awesim is 755 and ~/awesim/share is 755. But there is nothing on the details page of the app to indicate this.

This is tricky. An app that has 755 set on the app directory will be accessible to everybody that user can possibly share with (rendering the other FACLs useless). But for Open OnDemand, if you can only share with your group, this is a mute point. For AweSim, this is not a state you want to be in and you should at least be aware of what is happening.

Maybe a warning like:

![screen shot 2016-10-18 at 10 35 02 am](https://cloud.githubusercontent.com/assets/512333/19482256/8e6c4b14-951e-11e6-91c5-7a48e344b037.png)

There is probably a better solution for this though.

**Comment by nickjer** [comment]
I am fine with a lint error along the lines of:

"App permissions are too permissive, please set app permissions to 750"

**Comment by ericfranz** [comment]
If we add a lint error like that, include the command in the lint error text that the user should run.

**Comment by ericfranz** [comment]
A better interface for permissions https://github.com/OSC/ood-dashboard/issues/271 will address this issue.
