### ISSUE TITLE
Missing lint: no one has access to app directory

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-dashboard#50]
Previously, we had a lint that verified up the directory tree that EVERYONE had rx to the "restart directory" because Apache and Passenger 4.0.21 needed that in order for apps to restart.

https://github.com/AweSim-OSC/awesim-cli/blob/3d32fca170a67db647bb3fef2028b68543edbb7e/lib/awesim/lint.rb#L39-L44

This also served to help new AweSim app developers, whose default permission on $HOME was 750, too restrictive to share an app with users outside of their group.

Now this is gone.

If I open a terminal and run `chmod 700 ~`, **no one can access my shared apps**. Yet there is no indication or lint error on my shared apps.

Like https://github.com/OSC/ood-dashboard/issues/49, this is a visibility issue. We need to let the user know, based on the current permissions for each of the directories who can actually access their apps.

**Comment by ericfranz** [comment]
For example, for an AweSim user, having 750 on their $HOME directory could be considered a problem (for which we previously raised a lint error), but for OnDemand users who can only share apps with their group this would not be a problem.

**Comment by nickjer** [comment]
We can add this as a lint error. Although, if a developer only specifically grants `awesim` users access to their home dir, then it will continue to raise the lint error. If we are fine with this then it shouldn't be too difficult to implement. Just test for 755 permissions all the way back to root.

**Comment by nickjer** [comment]
Is this still relevant? If a user doesn't have access to an app, do they need access to the restart file?

**Comment by ericfranz** [comment]
Not doing
