### ISSUE TITLE
Change the default app icon to a Font Awesome Gear

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-dashboard#52]

**Comment by nickjer** [comment]
Random google images search. You can do image searches if you give google the file.

**Comment by nickjer** [comment]
https://www.google.com/search?tbs=sbi:AMhZZisUSOnsvVCtzeWAPiAXTuUZRaNmL16GUe_1l8-7J5UMelVmf1qiGACS93_1SVY-Odjq1M_15X13LP53MTygin4KY14hvsABZCkqtBI5pey2d_15JP_1s9do5Gw7fBztvNklQvf55J5nCwUOT4HIKIdBupaSlkUAIGkN6pZhvRJQs3PXP3Mc6UeDiHRHKuSBUihF5SxyHJUTFlLen3U_1umqEJWYdfVSedPzUl9kqZ3DKcrcUt2P657Xw1vzB6BcNnABCNyJJCiOeiNQB5p8aDymuAvtV1BIzWeWRY4NTft_1dpqbGeo1CDx4d1X9z7fJvxntDtaX0bxzb_1NrB9qM8CSh_1k2Jp4_1XR0xy6444eZcuWEKUMHaelbllOJR8oQ6Ez9ELzalwUFnpSZCmvkK63HPs6lK7U1o43YvK-8qQyEbigzgdABf0Ug0_18eoGcYRah3FL_15x33eGzoaRLiDApMwER42AIKQJ4MLmbrTIlaWUNbE_1kLit7BOxGXQS3yoxBZFYJwvtO0esv9uiOMgrchH-iEJLzbjDd1nl1FI5yUi8B_1PigyFBZTaujYo0y6E5hmRbUbh2gKTRCqgYMhK7BcIXZr_18jzacW0o-x7SPQUh_1AX5GqKPsNuH8WJpTuBMCSoZXfy5k5oLXe7wOIZvLjL6W60t7-fR2ZEHmVOK_1iqffC6Zy77RQLHaPTR4kuPzWnDvZQ-_17f94oJhczLQaYKHTCec5-wyrw5MwjvWoC3-5cJ35vW53V3hRRPDDYvcYa7ffooZLLM3_1u_1P_1cjuf1CKOif8yeCUhskSRFfxlWHwNfskQ9Xj-nxv2lqNrEycNY2jEf_1mEHtXj2N9r66SFwkVMQq_1cJoGCfhhOUQdSqGN4G0UyiGW4eXze0_1Vj1SkKXU1VivZnfTnqKbYiGFVMfYn4OLwuT44ASUq57dFdDWt_1sDdgW74M4wi1Ic6ChW9jQpzwh1hyK8XXlGUe5qNG7umJbkC-1nH75BT5orIRtkhlbnr1lAYOJhiPFbkNRu8EKvbW1V9fYEuekBGNePqeMzN6HWBY4DiWu6IYJF-UWPYRpxU1z4NVWjwRCqNcfcRyMB7GJ-BWvEdiFQJJ5k8xfA9qWeYTf5mD3GUk15pu9tcgdw0UA-pKW-3KzsiOU6MHROe_19bbDiMWoElMx48IcZ2JuzOVXdheVPFOnrATZeWy81ug1vAsv1kia2G0diI-4hlvNSQuAIbm7G370FUM9aKvMPbG8Lw129YlelMcDa4sRgRKkAY5B0T6042V-BAsFuzRG99WVuyue3fmG-xbLLvSLi615ghxpkHePDKH6XPbtRwxz-lC22CoE452dODOgYnZ1ToJozyc2mDwI_1UA6bv4fUAK4RfzaxtBBsQOyNgpp3FzXKZTykMHGBT3y8clgwUvCCicy1w-nKoVYQh4f2F1Ftr_1vskPjBx_1DHo1Zax_1XYRSqXRrbAnpBoWW5nFeRinT7henl3EZOQ4MDhyTEnWOhDZb8H9XHrovpu-6SCWSnPyf3ElgyhRDe988OOX_1AoLJVG4nhUmQZBGNCKAR-WeA4-BR-3b0F6sOkCO604tDwe0di9toDZEpJJknDJog52VYYaR8DVAlepFzs&hl=en

**Comment by nickjer** [comment]
If it is proprietary, then we can replace it.

**Comment by ericfranz** [comment]
Looks like it is:

https://www.iconfinder.com/icons/703606/cogs_configure_options_process_settings_support_icon#size=512

**Comment by ericfranz** [comment]
![screen shot 2016-10-24 at 10 40 28 am](https://cloud.githubusercontent.com/assets/512333/19650567/c5bf5350-99d7-11e6-8e8e-927bae0e62d2.png)

Doesn't look terrible if there is no icon. Lets just drop the "default" icon altogether.

**Comment by nickjer** [comment]
In my opinion it looks a little bad with no default icons.

**Comment by ericfranz** [comment]
Changing the default icon to a Font Awesome gear.
