### ISSUE TITLE
Support specifying font awesome icons for apps

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-dashboard#57]
1. `OodApp#fa_icon` can delegate to manifest#fa_icon
2. manifests have a new field in yaml: `fa_icon: gear`
3. default value in manifest is `gear`
4. the logic of the dashboard will be that if icon.png is not present, use `fa_icon` instead

**Comment by ericfranz** [comment]
This will let us use the manifest to specify all the icons for all the sys apps that we currently use.

**Comment by ericfranz** [comment]
* another alternative is in manifest instead of `fa_icon: gear` we do `icon: fa-gear`  - could open up other options in future

**Comment by nickjer** [comment]
Not a fan of adding `fa_icon` to manifest. I prefer your latter suggestion a "bit" more.

Unfortunately I can't think of a better option right now.

**Comment by ericfranz** [comment]
okay, we will do:

* manifest: `icon: fa-gear`
* default is `fa-gear`
* for now, assume only valid value for `icon` in manifest is a font-awesome class name - but later we can support other values - so OodApp#fa_icon can still be added (and we can change this later as necessary)

**Comment by nickjer** [comment]
Maybe something like:

```yaml
icon: file://./path/to/image.png
icon: fa://gear
icon: http://my.cdn.com/img.png
```

**Comment by ericfranz** [comment]
```yaml
icon: fa://gear
```

and only support `fa://gear` for now. If icon.png is in root, use that instead.
