### ISSUE TITLE
Dashboard shell for Sandbox and Shared apps doesn't open to OOD_DEV_SSH_HOST

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-dashboard#60]
We deployed 1.4.0. In .env.local OOD_DEV_SSH_HOST is set to apps-test.awesim.org. However, when opening to the terminal of an app, we end up at the default host of the shell app, which is currently an Oakley login node.

**Comment by nickjer** [comment]
Could you give steps to reproduce this? I am unable to reproduce this behavior.

**Comment by ericfranz** [comment]
Clone the dashboard to ~/awesim/dev, incorrectly configure it, and access it. Launch shell from there. :-)

Not a bug.
