### ISSUE TITLE
Cannot get SSH location to show-up in Clusters drop-down

### ISSUE THREAD

**Issue by basilgohar** [OSC/ood-dashboard#68]
I installed the shell app and that made the Clusters menu app, but the drop-down is empty.  I have created a .env file in $oodpath/shell with the DEFAULT_SSHHOST set to localhost, IP address, and even oakley.osc.edu, but nothing is showing-up still.

**Comment by ericfranz** [comment]
Fixed by fixing https://github.com/OSC/ood-dashboard/issues/80
