### ISSUE TITLE
Update bin/setup to provide the initial installation steps

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-dashboard#83]
We could use `#!/bin/sh` and can use `scl enable` to do all of the specified steps.

https://robots.thoughtbot.com/bin-setup

So instead of instructing users to build the app like this:

> 2. Build the app (install dependencies and build assets)
>
>  ```sh
>  scl enable git19 nodejs010 rh-ruby22 -- bin/bundle install --path vendor/bundle
>  scl enable git19 nodejs010 rh-ruby22 -- bin/rake assets:precompile RAILS_ENV=production
>  scl enable git19 rh-ruby22 nodejs010 -- bin/rake tmp:clear
>  ```

We could do this:

> 2. Build the app (install dependencies and build assets)
>
>  ```sh
>  bin/setup
>  ```

Of course the negative of this is if there are other valid versions of the `scl` packages installed. Another option would be:

> 2. Build the app (install dependencies and build assets)
>
>  ```sh
>  scl enable git19 nodejs010 rh-ruby22 -- bin/setup
>  ```

A benefit is that the setup script could actually ask the installer questions and generate any .env or other files by default. The setup script could be written in Ruby or be a shell script.

It could be a powerful thing that the simplest installation of every ood app could be:

    git clone
    git checkout tags/vX.Y.Z
    scl enable git19 nodejs010 rh-ruby22 -- bin/setup

We could follow this convention for node and rails apps.

**Comment by ericfranz** [comment]
We have `.env.local.osc` and `config/initializers/ood.rb.osc` so we could offer an argument "site" i.e.:

    scl enable git19 nodejs010 rh-ruby22 -- bin/setup --site=osc

This would do the normal build steps after copying config/initializers/ood.rb.osc to config/initializers/ood.rb and .env.local.osc to .env.local

**Comment by brianmcmichael** [comment]
This has been implemented in all apps as a component of https://github.com/OSC/ood-apps-installer

In the dashboard particularly at https://github.com/OSC/ood-dashboard/pull/147
