### ISSUE TITLE
When creating a new product, if no Git remote is provided, throw an error, instead of creating a new app

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-dashboard#87]
When creating a "New Product", if I choose "Clone an existing repo" and forget to add the git remote for this repo and press Submit, but add a directory name, instead of throwing an error that git remote was not set, it creates a new app from the preinitialized app (as though I clicked Build a New App).

This was problematic for me because:

1. I clicked Clone Existing App because I wanted to clone an existing app, but when I accidentally pressed Enter after typing the Directory name in, it created a new app instead of cloning the app I wanted to clone
2. When I tried to clone the app again, the Directory name was now taken because it had created a new app in place where I wanted to clone an app to

Instead, require the Git remote to not be blank. 

![screen shot 2016-11-30 at 5 00 25 pm](https://cloud.githubusercontent.com/assets/512333/20773170/84f3b0aa-b71e-11e6-892d-bbfb6d448108.png)

Or it might be best just to instruct the user what to do:

![screen shot 2016-11-30 at 4 57 46 pm](https://cloud.githubusercontent.com/assets/512333/20773178/90a7d6ce-b71e-11e6-8921-f68f2ef70a2e.png)

Or offer a link to build a new app in the help text:

![screen shot 2016-11-30 at 4 59 15 pm](https://cloud.githubusercontent.com/assets/512333/20773181/940b9c1a-b71e-11e6-8c2a-4c1aa211fa58.png)

**Comment by nickjer** [comment]
This is a bug. Since both forms for creating a new app post to the same URL, it determines that it is a git clone app if the git URL is provided otherwise it assumes it is a new app from the template.

**Comment by nickjer** [comment]
Using a hidden field that describes what form (or what method to create the product from) sent in the new product request would be the simplest solution.
