### ISSUE TITLE
Something broke between apps-dev and apps-test

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-dashboard#92]
This appears only on apps-dev:

![image](https://cloud.githubusercontent.com/assets/4260509/20975223/cfb1a310-bc6c-11e6-92e1-470365778176.png)

**Comment by ericfranz** [comment]
Will you list the steps to reproduce?

**Comment by nickjer** [comment]
I go here:

https://apps-dev.awesim.org/pun/sys/dashboard/admin/dev/products

I also have a product with no manifest.

**Comment by ericfranz** [comment]
A bug on a branch. This didn't affect master. https://github.com/OSC/ood-dashboard/pull/90
