### ISSUE TITLE
Product model aware of type of app

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-dashboard#93]
Not only should the Product model be aware of the type of app:

  - passenger_ruby
  - passenger_nodejs
  - passenger_python
  - passenger_meteor
  - undetermined

The "details" view should conform to this app type (e.g., don't display `Bundle Install` button for a non-passenger_ruby app)

Can use the following for default determining app type:

https://www.phusionpassenger.com/library/config/nginx/reference/#passenger_startup_file

**Comment by ericfranz** [comment]
If we could add validations to an instance at runtime, then we could get buy without any subtypes. Just 1 or 2 sets of conditionals. But adding rails validations to instances at runtime may be problematic.

Maybe Rails 4 offers some other mechanism to have the validations run based on a certain value returned by an instance method.

**Comment by ericfranz** [comment]
Here it is: http://guides.rubyonrails.org/active_record_validations.html#conditional-validation

So validations should specify the app type that they are for, unless they should run for every app, such as a missing manifest file.
