### ISSUE TITLE
Editing manifest through web interface deletes many attributes

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-dashboard#96]
Steps to reproduce:

1. Develop -> My Sandbox Apps -> New Product -> Clone Existing App
2. Clone the https://github.com/OSC/bc_osc_oakley_desktop app
3. Edit the manifest and change the description
4. Open a shell to the directory and do git diff

```diff
efranz@webtest04:~/awesim/dev/bc_osc_oakley_desktop (master)$ git diff
diff --git a/manifest.yml b/manifest.yml
index 833efd8..7113491 100644
--- a/manifest.yml
+++ b/manifest.yml
@@ -1,10 +1,5 @@
 ---
 name: Oakley Desktop
-description: |-
-  **Oakley Desktop** provides a remote desktop to one or more compute nodes on
-  the Oakley cluster at the Ohio Supercomputer Center (OSC).
-icon: fa://desktop
-category: Desktops
-subcategory: Interactive HPC
-role: ihpc
-url: /pun/dev/vncsim/%{app_token}/sessions
+description: "**Oakley Desktop** provides a remote desktop to one or more compute
+  nodes on\r\nthe Oakley cluster at the Ohio Supercomputer Center (OSC).\r\n\r\nWhat
+  happens?"
efranz@webtest04:~/awesim/dev/bc_osc_oakley_desktop (master)$ 
```

**Comment by ericfranz** [comment]
You have experience with this in Job Constructor. A similar solution probably is appropriate.

**Comment by nickjer** [comment]
My suggestion would be to read the YAML as a hash, merge in the keys that the form sets, and then dump the hash back to the YAML.

**Comment by nickjer** [comment]
Also, if an exception is raised while parsing the YAML (invalid YAML), you might want to rescue and overwrite the YAML with just the values set in the form.
