### ISSUE TITLE
Errors when creating new product using "Build new app"

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-dashboard#99]
Experienced two issues with this. One in development and another in existing production app. They appear to be different errors but they may stem from the same cause.

To recreate:
"Develop" dropdown -> "My Sandbox Apps" -> click "Build New App" -> Fill out form and click "Submit"

In development:

![newproducterror](https://cloud.githubusercontent.com/assets/2374718/21268235/cc8d455c-c37b-11e6-9b03-64c14415419c.png)

In production:

![newproducterrorawesim](https://cloud.githubusercontent.com/assets/2374718/21268248/de973780-c37b-11e6-8569-02b7e51ac66b.png)

The production app shows the error message but still creates the folder. It does not perform the bundle install.

**Comment by ericfranz** [comment]
Opened #101 for the first issue.

This problem is addressed in 3984dc79d8cea4044860b328c0a7a0c6f44c4810
